# Generated by Django 4.1.7 on 2023-03-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeApiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='starts',
            new_name='stars',
        ),
    ]
